devops_blog/backend/models.py
#!/usr/bin/env python
# -*- coding:utf8 -*-
"""
	mongo_mo
"""
from .. import mongo_db
from devops_blog.utils import timeTools
from datetime import datetime

time_tools = timeTools()

class Post(mongo_db.Document):
    #id = mongo_db.IntField()
    title = mongo_db.StringField()
    body = mongo_db.StringField()
    ctime = mongo_db.DateTimeField(default=datetime.now())
    category_id = mongo_db.IntField(default=None)

    #def __init__(self,title,body):
    #    title = self.title
    #    body = self.body


class Category(mongo_db.Document):
    #id = mongo_db.IntField()
    name = mongo_db.StringField()

    #def __init__(self,name):
     #   name = self.name

devops_blog/blog/models.py
#!/usr/bin/env python
# -*- coding:utf8 -*-
"""
    mysql model 类
"""
from .. import mysql_db
from datetime import datetime


# 多对多配置 用户<--->用户组
users = mysql_db.Table('users_groups',
    mysql_db.Column('user_id', mysql_db.Integer, mysql_db.ForeignKey('fb_users.id')),
    mysql_db.Column('userGroup_id', mysql_db.Integer, mysql_db.ForeignKey('fb_userGroups.id'))
    )


# 用户组
class userGroup(mysql_db.Model):
    __tablename__ = "fb_userGroups"
    id = mysql_db.Column(mysql_db.Integer, primary_key=True,autoincrement=True)
    # 多对多关联用户组
    users = mysql_db.relationship('User', secondary=users,backref=mysql_db.backref('userGroup', lazy='dynamic'))
    # 角色关联(一对多)
    roles = mysql_db.relationship('Role', backref='userGroups',lazy='dynamic')
    def __init__(self,userGroupName):
        self.userGroupName = userGroupName

    def __repr__(self):
        return "<userGroup %r>" %self.userGroupName

# 用户
class User(mysql_db.Model):
    __tablename__ = "fb_users"
    id = mysql_db.Column(mysql_db.Integer, primary_key=True,autoincrement=True)
    # 用户名
    username = mysql_db.Column(mysql_db.String(80), unique=True,comment='用户名')
    # 邮箱
    email = mysql_db.Column(mysql_db.String(120), unique=True,comment='邮箱')
    # 微信昵称
    weixin_name = mysql_db.Column(mysql_db.String(120),  default='',comment='微信昵称')
    # 逻辑删除
    is_del = mysql_db.Column(mysql_db.Boolean,default=False,comment='逻辑删除')
    # 创建时间
    join_date = mysql_db.Column(mysql_db.DateTime,default=datetime.now())
    # 用户组外键
    userGroup_Id = mysql_db.Column(mysql_db.Integer,mysql_db.ForeignKey('fb_userGroups.id'),comment='关联一级用户组,多对一')

    def __init__(self, username, email):
        self.username = username
        self.email = email

    def __repr__(self):
        return '<User %r>' % self.username


class Nav(mysql_db.Model):
    __tablename__ = "fb_navs"
    id = mysql_db.Column(mysql_db.Integer,primary_key=True,autoincrement=True)
    # 一级导航栏标题
    navTitle = mysql_db.Column(mysql_db.String(120),unique=True,nullable=False,comment='一级导航栏标题')
    # 一级导航栏url,可以为空,默认为空
    navUrl = mysql_db.Column(mysql_db.String(120),nullable=True,default='',index=True,comment='一级导航栏url')
    # 前后台导航栏分类
    navType = mysql_db.Column(mysql_db.Boolean(),default=False,comment='导航栏分类,默认为后台导航栏')
    # 逻辑删除
    is_del = mysql_db.Column(mysql_db.Boolean(),default=False,comment='逻辑删除')
    # 关联用户组权限
    subnavs = mysql_db.relationship('subNav', backref='nav',lazy='dynamic')
    # 角色外键 
    role_id = mysql_db.Column(mysql_db.Integer,mysql_db.ForeignKey('fb_roles.id'),comment='关联角色,多对一')
    def __init__(self,navTitle,navUrl,navType,role_id):
        self.navTitle = navTitle
        self.navType = navType
        self.navUrl = navUrl
        self.role_id = role_id
    def __repr__(self):
        return "<Nav %r>" %self.navTitle


# 二级导航栏
class subNav(mysql_db.Model):
    __tablename__ = "fb_subnavs"
    id = mysql_db.Column(mysql_db.Integer,primary_key=True,autoincrement=True)
    # 二级导航栏标题
    title = mysql_db.Column(mysql_db.String(120),index=True,unique=True,nullable=False,default='#',comment='二级导航栏标题')
    # 二级导航栏url
    nav_url = mysql_db.Column(mysql_db.String(200),index=True,unique=True,nullable=False,default='#',comment='二级导航栏url')
    # 一级导航栏外键
    nav_Id = mysql_db.Column(mysql_db.Integer,mysql_db.ForeignKey('fb_navs.id'),comment='关联一级导航栏,多对一')
    # 逻辑删除
    is_del = mysql_db.Column(mysql_db.Boolean,default=False,comment='逻辑删除')

    def __init__(self,title,nav_url):
        self.title = title
        self.nav_url = nav_url

    def __repr__(self):
        return "<subNav %r>" %self.title


# 用户角色权限表
class Role(mysql_db.Model):
    __tablename__ = "fb_roles"
    id = mysql_db.Column(mysql_db.Integer,primary_key=True,autoincrement=True)
    # 角色名称
    roleName = mysql_db.Column(mysql_db.String(120),unique=True,index=True,nullable=False,default='普通用户',comment='角色名称')
    # 一级导航栏外键  一个角色有多个导航栏
    navs = mysql_db.relationship('Nav', backref='role',lazy='dynamic')
    # 用户组外键
    fb_userGroup_Id = mysql_db.Column(mysql_db.Integer,mysql_db.ForeignKey('fb_userGroups.id'),comment='用户组权限外键')

    def __init__(self,roleName):
        self.roleName = roleName

    def __repr__(self):
        return "<Role %r>" %self.roleName

devops_blog/__init__.py
#!/usr/bin/env python
# -*- coding:utf8 -*-
"""
	flask 启动参数
"""
# 导入Falsk 应用
from flask import Flask, jsonify
# 导入模板应用
from flask import render_template
# 导入falsk bootstrap 应用
from flask_bootstrap import Bootstrap
# 导入 sqlAlchemy python orm 模块
from flask_sqlalchemy import SQLAlchemy
# 导入 sqlAlchemy mongo orm 模块
from flask_mongoalchemy import MongoAlchemy
# 导入 falsk_migrate 
from flask_migrate import Migrate
# 导入flask restfull api
from flask_restful import Api
# 导入配置文件全局环境变量
from devops_blog.config import flask_env_config
import os

# 初始化mysql数据库连接
mysql_db = SQLAlchemy()
# 初始化mongo数据库连接
mongo_db = MongoAlchemy()
migrate = Migrate()

# 定义一个创建app应用并且初始化的方法
def create_app(flask_env='default'):
    # 创建flask应用
    app = Flask(__name__)
    app.config.from_object(flask_env_config[flask_env])
    # 初始化bootstrap
    Bootstrap(app)
    # 初始化mysql数据库连接
    mysql_db.init_app(app)
    # 初始化mongo数据库连接
    mongo_db.init_app(app)
    # 初始化mysql据库migrate 
    migrate.init_app(app,mysql_db,directory=os.path.abspath(os.path.dirname(__file__))+os.sep+"migrations")
    # 导入自定义蓝图模块
    from .blog import blog as blog_bp
    # 注册蓝图 
    app.register_blueprint(blog_bp,url_prefix='/blog')
    app.add_url_rule('/',endpoint='blog.index')
    from .backend import backend as backend_bp
    app.register_blueprint(backend_bp,url_prefix='/houtai')
    return app

devops_blog/backend/__init__.py
#!/usr/bin/env python
# -*- coding:utf8 -*-
from flask import Blueprint

backend = Blueprint('backend',__name__)

from . import views,api_resources
from flask import make_response
from flask_restful import Resource,Api
from .api_resources import ApiTest,NavApi,NavListApi
import json

# 注册蓝图api
api = Api(backend,catch_all_404s=True)

# 添加api 可插拔式路由
api.add_resource(ApiTest,'/apitest')
api.add_resource(NavApi,'/Nav','NavApi')
api.add_resource(NavListApi,'/NavList','NavListApi')

devops_blog/backend/views.py
#!/usr/bin/env python
# -*- coding:utf8 -*-
from flask import render_template,request, make_response, url_for,current_app,jsonify,g
from . import backend
import os,datetime,random
from .models import Post,Category


json_test={
        "code": 0
        ,"msg": ""
        ,"count": 3000000
        ,"data": [{
            "id": "10001"
            ,"username": "杜甫"
            ,"email": "xianxin@layui.com"
            ,"sex": "男"
            ,"city": "浙江杭州"
            ,"sign": "点击此处，显示更多。当内容超出时，点击单元格会自动显示更多内容。"
            ,"experience": "116"
            ,"ip": "192.168.0.8"
            ,"logins": "108"
            ,"joinTime": "2016-10-14"
            }, {
                "id": "10002"
                ,"username": "李白"
                ,"email": "xianxin@layui.com"
                ,"sex": "男"
                ,"city": "浙江杭州"
                ,"sign": "君不见，黄河之水天上来，奔流到海不复回。 君不见，高堂明镜悲白发，朝如青丝暮成雪。 人生得意须尽欢，莫使金樽空对月。 天生我材必有用，千金散尽还复来。 烹羊宰牛且为乐，会须一饮三百杯。 岑夫子，丹丘生，将进酒，杯莫停。 与君歌一曲，请君为我倾耳听。(倾耳听 一作：侧耳听) 钟鼓馔玉不足贵，但愿长醉不复醒。(不足贵 一作：何足贵；不复醒 一作：不愿醒/不用醒) 古来圣贤皆寂寞，惟有饮者留其名。(古来 一作：自古；惟 通：唯) 陈王昔时宴平乐，斗酒十千恣欢谑。 主人何为言少钱，径须沽取对君酌。 五花马，千金裘，呼儿将出换美酒，与尔同销万古愁。"
                ,"experience": "12"
                ,"ip": "192.168.0.8"
                ,"logins": "106"
                ,"joinTime": "2016-10-14"
                ,"LAY_CHECKED": True
                }, {
                    "id": "10003"
                    ,"username": "王勃"
                    ,"email": "xianxin@layui.com"
                    ,"sex": "男"
                    ,"city": "浙江杭州"
                    ,"sign": "人生恰似一场修行"
                    ,"experience": "65"
                    ,"ip": "192.168.0.8"
                    ,"logins": "106"
                    ,"joinTime": "2016-10-14"
                    }, {
                        "id": "10004"
                        ,"username": "李清照"
                        ,"email": "xianxin@layui.com"
                        ,"sex": "女"
                        ,"city": "浙江杭州"
                        ,"sign": "人生恰似一场修行"
                        ,"experience": "666"
                        ,"ip": "192.168.0.8"
                        ,"logins": "106"
                        ,"joinTime": "2016-10-14"
                        }, {
                            "id": "10005"
                            ,"username": "冰心"
                            ,"email": "xianxin@layui.com"
                            ,"sex": "女"
                            ,"city": "浙江杭州"
                            ,"sign": "人生恰似一场修行"
                            ,"experience": "86"
                            ,"ip": "192.168.0.8"
                            ,"logins": "106"
                            ,"joinTime": "2016-10-14"
                            }, {
                                    "id": "10006"
                                    ,"username": "贤心"
                                    ,"email": "xianxin@layui.com"
                                    ,"sex": "男"
                                    ,"city": "浙江杭州"
                                    ,"sign": "人生恰似一场修行"
                                    ,"experience": "12"
                                    ,"ip": "192.168.0.8"
                                    ,"logins": "106"
                                    ,"joinTime": "2016-10-14"
                                    }, {
                                            "id": "10007"
                                            ,"username": "贤心"
                                            ,"email": "xianxin@layui.com"
                                            ,"sex": "男"
                                            ,"city": "浙江杭州"
                                            ,"sign": "人生恰似一场修行"
                                            ,"experience": "16"
                                            ,"ip": "192.168.0.8"
                                            ,"logins": "106"
                                            ,"joinTime": "2016-10-14"
                                            }, {
                                                    "id": "10008"
                                                    ,"username": "贤心"
                                                    ,"email": "xianxin@layui.com"
                                                    ,"sex": "男"
                                                    ,"city": "浙江杭州"
                                                    ,"sign": "人生恰似一场修行"
                                                    ,"experience": "106"
                                                    ,"ip": "192.168.0.8"
                                                    ,"logins": "106"
                                                    ,"joinTime": "2016-10-14"
                                                                                                                                                                                                                                 }]
                                                                                                                                                                                                                    }  


@backend.route('/list_comment',methods=('GET','POST'))
def get_list_comments():
    return jsonify(json_test)


@backend.route('/addNavModal.html')
def test():
    return render_template('houtai/addNavModal.html')


@backend.route('/addFNav',methods=('POST',))
def addFNavs1():
    res = dict()
    res['code'] = 200
    res['data'] = 'ok'
    return jsonify(res)


@backend.route('/list_navs',methods=('GET','POST'))
def listNavs():
    print(g)
    return jsonify(g.get('navs'))


@backend.route('/system_settings')
def sys_settings():
    return render_template('houtai/system.html')


@backend.route('/')
def index():
    return render_template("houtai/index.html")


@backend.route('/comment')
def comment_list():
    return render_template("blog/comment_list.html")


def gen_rnd_filename():
    filename_prefix = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    return '%s%s' % (filename_prefix, str(random.randrange(1000, 10000)))


@backend.route('/edit',methods=('GET','POST'))
def edit():
    error = ''
    url = ''
    filename = ''
    """CKEditor file upload"""
    callback = request.args.get("CKEditorFuncNum")
    if request.method == 'GET': 
    	return render_template('blog/edit.html')
    elif request.method == 'POST' and 'upload' not in request.files:
        title = request.form.get('subject')
        data = request.form.get('content')
        post = Post(title=title,body=data)
        category = Category()
        post.save()
        response = make_response(data)
        response.headers["Content-Type"] = "text/html"
        return response
    elif request.method == 'POST' and 'upload' in request.files:
        fileobj = request.files['upload']
        fname, fext = os.path.splitext(fileobj.filename)
        rnd_name = '%s%s' % (gen_rnd_filename(), fext)
        filepath = os.path.join(current_app.static_folder, 'upload', rnd_name)
        # 检查路径是否存在，不存在则创建
        dirname = os.path.dirname(filepath)
        if not os.path.exists(dirname):
            try:
                os.makedirs(dirname)
            except:
                error = 'ERROR_CREATE_DIR'
        elif not os.access(dirname, os.W_OK):
            error = 'ERROR_DIR_NOT_WRITEABLE'
        if not error:
            fileobj.save(filepath)
            filename = '%s/%s' % ('upload', rnd_name)
            url = url_for('static', filename=filename)
    else:
        error = 'post error'
    res = """

<script type="text/javascript">
  window.parent.CKEDITOR.tools.callFunction(%s, '%s', '%s');
</script>

""" % (callback, url, error)
    response = make_response(res)
    response.headers["Content-Type"] = "text/html"
    return jsonify(uploaded=1, url=url, filename=filename)
    #return response

devops_blog/blog/__init__.py
#!/usr/bin/env python
# -*- coding:utf8 -*-
from  flask import Blueprint

# 创建蓝图 
blog = Blueprint('blog',__name__)

from . import views

devops_blog/blog/views.py
#!/usr/bin/env python
# -*- coding:utf8 -*-
from flask import render_template,current_app
from . import blog
from .. import mysql_db,mongo_db


# 创建一个视图应用,博客首页
@blog.route('/',methods=('GET','POST'))
def index():
    return render_template('base/base.html')


@blog.route('/test')
def test():
    return render_template("houtai/index.html")

devops_blog/templates/blog/comment_list.html
{% extends "houtai/houtai_index.html" %}
{% block title %} 文章列表 {% endblock  %}
{% block nav %} 
    <style>
        .blog-main{
            margin-left:-60px;
        }
    </style>
{% endblock %}

{% block article_title %}

{% endblock %}

{% block special_index %}
{% endblock %}
{% block article %}
    <table class="layui-hide" id="test" lay-filter="test"></table>

    <script type="text/html" id="toolbarDemo">
    <div class="layui-btn-container">
        <button class="layui-btn layui-btn-sm" lay-event="getCheckData">获取选中行数据</button>
        <button class="layui-btn layui-btn-sm" lay-event="getCheckLength">获取选中数目</button>
        <button class="layui-btn layui-btn-sm" lay-event="isAll">验证是否全选</button>
      </div>
    </script>

    <script type="text/html" id="barDemo">
    <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
      <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>



    <script>
    layui.use('table', function(){
            var table = layui.table;

            table.render({
    elem: '#test'
    ,height: 500
    ,width: 1020
    ,url:'list_comment'
    ,toolbar: '#toolbarDemo'
    ,title: '用户数据表'
    ,cols: [[
    {type: 'checkbox', fixed: 'left'}
    ,{field:'id', title:'ID', width:80, fixed: 'left', unresize: true, sort: true}
    ,{field:'username', title:'用户名', width:120, edit: 'text'}
    ,{field:'email', title:'邮箱', width:150, edit: 'text', templet: function(res){
    return '<em>'+ res.email +'</em>'
    }}
    ,{field:'sex', title:'性别', width:80, edit: 'text', sort: true}
    ,{field:'city', title:'城市', width:100}
    ,{field:'sign', title:'签名'}
    ,{field:'experience', title:'积分', width:80, sort: true}
    ,{field:'ip', title:'IP', width:120}
    ,{field:'logins', title:'登入次数', width:100, sort: true}
    ,{field:'joinTime', title:'加入时间', width:120}
    ,{fixed: 'right', title:'操作', toolbar: '#barDemo', width:150}
    ]]
            ,page: true
            });

    //头工具栏事件
    table.on('toolbar(test)', function(obj){
            var checkStatus = table.checkStatus(obj.config.id);
            switch(obj.event){
            case 'getCheckData':
            var data = checkStatus.data;
            layer.alert(JSON.stringify(data));
            break;
            case 'getCheckLength':
            var data = checkStatus.data;
            layer.msg('选中了：'+ data.length + ' 个');
            break;
            case 'isAll':
            layer.msg(checkStatus.isAll ? '全选': '未全选');
            break;
            };
            });

    //监听行工具事件
    table.on('tool(test)', function(obj){
            var data = obj.data;
            //console.log(obj)
            if(obj.event === 'del'){
            layer.confirm('真的删除行么', function(index){
                obj.del();
                layer.close(index);
                });
            } else if(obj.event === 'edit'){
            layer.prompt({
    formType: 2
    ,value: data.email
    }, function(value, index){
    obj.update({
    email: value
    });
    layer.close(index);
    });
            }
            });
    });
    </script>
{% endblock %}

{% block right %} 

{% endblock %}


{% block footer %} 

{% endblock %}

devops_blog/templates/blog/edit.html
{% extends "base/base.html" %}
{% block title %} 后台文章编辑 {% endblock  %}
{% block nav %}
{#    引入CKEditor#}
<script type="text/javascript" src="{{  url_for('static',filename='plugins/ckeditor/ckeditor.js') }}"></script>
{% endblock %}

{% block article_title %}
<center><h3>在线编辑文章</h3></center>
<hr/>
{% endblock %}

{% block article %}
<div class="row">   
 <form method="post" class="form-horizontal" role='form' action="{{ url_for('backend.edit') }}" enctype="multipart/form-data">
  
  <div class="form-group">
      <label for="category"  class="col-sm-2 control-label">请选择文章分类</label>
    <div class="col-sm-10">
            <select class="form-control" name="categorys" id="category" placeholder="请选择文章分类">
                 <option></option>
            </select>
    </div>
  </div>

  <div class="form-group">
      <label for="title"  class="col-sm-2 control-label">文章标题</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="subject" id="title" placeholder="请输入文章标题" />
    </div>
  </div>
  <div class="form-group">
    <label for="content" class="col-sm-2 control-label">文章内容</label>
    <div class="col-sm-10">
      <textarea name="content" class="form-control" id="content" placeholder="文章内容"></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <button type="submit" class="btn btn-primary" value="立即发布" style="margin: 0px 810px;">立即发布</button>
    </div>
  </div>
   </form>
</div>
	{#   替换textarea  #}
        <script type="text/javascript">
            CKEDITOR.replace('content', {
	{#   开启上传功能，配置上传路径  #}
                filebrowserUploadUrl: "{{ url_for('backend.edit') }}",
            });
        </script>

{% endblock %}

{% block right %} 
	
{% endblock %}

devops_blog/templates/blog/temp.html
{% extends "base/base.html" %}
{% block title %} 后台文章编辑 {% endblock  %}
{% block nav %} 

{% endblock %}

{% block article_title %}

{% endblock %}

{% block article %}

 {% endblock %}

{% block right %} 

{% endblock %}


{% block footer %} 

{% endblock %}

devops_blog/templates/blog/test.html
{% extends "bootstrap/base.html" %}
{% block title %}This is an example page{% endblock %}
{% block navbar %}
<div class="navbar navbar-fixed-top">
<link rel="stylesheet" href="{{ url_for('static', filename='test.css') }}">
</div>
{% endblock %}

{% block content %}
  <h1>Hello, Bootstrap</h1>
	<h2>这里是base.html</h2>
{% endblock %}